### ISSUE TITLE
file listing doesn't show after switching to another archive

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/dat-desktop#16]

**Comment by juliangruber** [comment]
manually listing files instead of through hyperdrive-ui works, but i assume it's a bug somewhere in the yo-yo stack

**Comment by karissa** [comment]
this might be your culprit: https://github.com/juliangruber/dat-desktop/blob/master/lib/render.js#L26

`yo` might not be able to distinguish the diff between the old hyperdrive-ui and the new one here? have you tried updating the `hyperdrive-ui` instance separately with `yo.update` on click?

@maxogden @shama do you know why this is not working?

**Comment by juliangruber** [comment]
@karissa yep. `hyperdrive-ui()` is just returning dom, yo should be able to diff it. the problem as far as i understand is that hyperdrive will modify the returned dom after it has been rendered, probably some references break...

if we initialize `hyperdrive-ui` with the full `entries` array and it doesn't have to do any asynchronous work, i'm quite sure the rendering will work as expected.

**Comment by shama** [comment]
It's likely because [this line](https://github.com/karissa/hyperdrive-ui/blob/master/index.js#L68) is referencing an element that is no longer in the DOM.

The easiest way to fix is use `document.querySelector()` to find the actual element in the DOM when calling `yo.update()`.

Or another strategy is send an action up when the `entries` have changed and leave it to the parent to render down again.

**Comment by juliangruber** [comment]
> Or another strategy is send an action up when the entries have changed and leave it to the parent to render down again.

that's interesting, i'll give it a try :)

**Comment by juliangruber** [comment]
@shama what would you then do about the stream the widget creates internally? it def. seems to me that this requires some lifecycle management

**Comment by laurengarcia** [comment]
i brought this up with max, too, @juliangruber and he recommended checking out choo
https://www.npmjs.com/package/choo

**Comment by shama** [comment]
@juliangruber I try to keep the models and views separate. That will let the app control the lifecycle.

The widget just accepts some generic data as input and returns an element. As events occur in that element, actions (just callbacks) are sent out. The app manipulates the model, builds the new data and gives it to the widget to render again.

Widgets can update themselves but best for only internal reasons not related to changes in the state. Such as adding an animation class or even maybe the widget does create a stream internally but when it comes time to manipulate the state, it sends the action out to let the app decide how to change the state instead.

If the author wants the widget to be a drop in thing, they just need to be aware the element last rendered won't always be the element in the DOM. They'll need to find that element with `document.querySelector()` if it needs to update that element in the DOM.
