### ISSUE TITLE
why not support folder sync

### ISSUE THREAD

**Issue by nolotus** [juliangruber/dat-desktop#56]
when create new dat ,it not support folder.just for single file.

**Comment by karissa** [comment]
working on this, once we integrate dat-js in #44 it should do that!

**Comment by nolotus** [comment]
how long ?i want use dat build a Distributed blog platform.could you give me some suggest.

**Comment by karissa** [comment]
I think you'll want to use the underlying modules for that. This is more of a user-facing app for dat. Try looking at http://github.com/mafintosh/hyperdrive and http://github.com/beakerbrowser/beaker

**Comment by juliangruber** [comment]
dat-desktop in its current version actually allows you to share folders. can you try again after upgrading?
