### ISSUE TITLE
consider choo migration

### ISSUE THREAD

**Issue by karissa** [juliangruber/dat-desktop#57]
cc @yoshuawuyts

**Comment by karissa** [comment]
probably should merge the update-design branch first

**Comment by yoshuawuyts** [comment]
yeah, feel this might be a good idea - right now we're pretty light on logic so it's not an issue - but once we start adding more moving parts having a bit more structure could help with collaborating for sure :sparkles:

**Comment by yoshuawuyts** [comment]
@juliangruber seemed to be keen on the idea too. Closing in favor of https://github.com/juliangruber/dat-desktop/issues/61
